import path from "path";
import { FOLDERS } from "./lib/config";
import { CIVILIZATIONS } from "./lib/config/civs";
import { getAllUnits } from "./lib/files/readUnitData";
import { writeJson } from "./lib/files/writeUnitData";

/** Creates index files for units */
(async () => {
  const units = await getAllUnits();
  writeJson(path.join(FOLDERS.UNITS.DATA, "all.json"), {
    __note__: "This is file is autogenerated, do not edit it manually",
    __version__: "0.0.1",
    data: units,
  });

  Object.values(CIVILIZATIONS).forEach((civ) => {
    writeJson(path.join(FOLDERS.UNITS.DATA, `${civ.slug}.json`), {
      __note__: "This is file is autogenerated, do not edit it manually",
      __version__: "0.0.1",
      civ,
      data: units.filter((u) => u.civs.includes(civ.abbr)),
    });
  });
})();
