export const CIVILIZATIONS = {
  ab: {
    name: "Abbasid Dynasty",
    abbr: "ab",
    slug: "abbasid",
    attribName: "abbasid",
  },
  ay: {
    name: "Ayyubids",
    abbr: "ay",
    slug: "ayyubids",
    attribName: "abbasid_ha_01",
  },
  by: {
    name: "Byzantines",
    abbr: "by",
    slug: "byzantines",
    attribName: "byzantine",
  },
  ch: {
    name: "Chinese",
    abbr: "ch",
    slug: "chinese",
    attribName: "chinese",
  },
  de: {
    name: "Delhi Sultanate",
    abbr: "de",
    slug: "delhi",
    attribName: "sultanate",
  },
  en: {
    name: "English",
    abbr: "en",
    slug: "english",
    attribName: "english",
  },
  fr: {
    name: "French",
    abbr: "fr",
    slug: "french",
    attribName: "french",
  },
  hr: {
    name: "Holy Roman Empire",
    abbr: "hr",
    slug: "hre",
    attribName: "hre",
  },
  ja: {
    name: "Japanese",
    abbr: "ja",
    slug: "japanese",
    attribName: "japanese",
  },
  je: {
    name: "Jeanne d'Arc",
    abbr: "je",
    slug: "jeannedarc",
    attribName: "french_ha_01",
  },
  ma: {
    name: "Malians",
    abbr: "ma",
    slug: "malians",
    attribName: "malian",
  },
  mo: {
    name: "Mongols",
    abbr: "mo",
    slug: "mongols",
    attribName: "mongol",
  },
  od: {
    name: "Order of the Dragon",
    abbr: "od",
    slug: "orderofthedragon",
    attribName: "hre_ha_01",
  },
  ot: {
    name: "Ottomans",
    abbr: "ot",
    slug: "ottomans",
    attribName: "ottoman",
  },
  ru: {
    name: "Rus",
    abbr: "ru",
    slug: "rus",
    attribName: "rus",
  },
  zx: {
    name: "Zhu Xi's Legacy",
    abbr: "zx",
    slug: "zhuxi",
    attribName: "chinese_ha_01",
  },
} as const;
